baseurl = "http://kirillpavlov.com/"
googleAnalytics = "UA-48154141-1"
title = "Development and Analytics Blog"

[permalinks]
  # Change the permalink format for the 'post' content type.
  post = "/blog/:year/:month/:day/:title/"
