# Default page metadata, used when the specific page doesn't set its own.
defaultDescription = "Personal website with the blog about technologies, software development and data analytics"
defaultKeywords = "blog,software,development,analytics,data mining,data science"

author = "Kirill Pavlov"
disqusShortname = "kirillpavlovcom"
